name: Build Go binaries with all extensions enabled

on: 
  repository_dispatch:
    types: [my-release]

env:
    VERSION: ${{ github.event.client_payload.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3

      - name: Get builder
        shell: bash
        run: curl -O https://raw.githubusercontent.com/xxxserxxx/gotop-builder/master/build.go

      - name: Generate gotop.go
        shell: bash
        run: go run ./build.go -r ${VERSION} github.com/xxxserxxx/gotop-remote github.com/xxxserxxx/gotop-nvidia
        env:
            VERSION: ${{ github.event.client_payload.tag }}

      - name: Compile
        shell: bash
        run: go build -o gotop -ldflags "-extldflags '-static' -X main.Version=${VERSION}+nvidia+remote -X main.BuildDate=$(date +%Y%m%dT%H%M%s)" ./gotop.go
        env:
            VERSION: ${{ github.event.client_payload.tag }}

      - name: Pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.client_payload.tag }}+nvidia+remote"
          draft: false
          title: "${{ github.event.client_payload.tag }} with NVidia & Remote extensions"
          files: gotop
